title: Scala Days | The premier Scala conference
name: Scala Days
description: The premier Scala conference returns in 2025
author: 
keywords: scala, scala center
baseurl: ""
email: "info@scaladays.org"
twitter_username: "@scaladays"
social_image: "/img/social-card.png"

sass:
    sass_dir: _sass
    style: compressed

plugins:
  - jekyll-github-metadata
  - jekyll-hostname
  - jekyll-feed
  - jekyll-sitemap

collections:
  editions:
    output: true
    permalink: /editions/:path

links:
  code-of-conduct: https://scala-lang.org/conduct/

defaults:
  - scope:
      path: "_editions/2025/talks/"
    values:
      layout: "schedule-detail"
  - scope:
      path: "_editions/2025/workshops/"
    values:
      layout: "workshops-detail"

include:
  - .well-known